version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from photo files"
    cmds:
      - protoc -I proto -I /Users/dimamuravskij/programming/go/protos/libs/protoc-gen-validate proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative --validate_out="lang=go,paths=source_relative:./gen/go"
